@startuml
'https://plantuml.com/class-diagram

interface BeanFactory {}
interface MessageSource {}
interface EnvironmentCapable {}
interface ApplicationEventPublisher {}
interface ResourceLoader {}
interface ApplicationContext extends BeanFactory, MessageSource, EnvironmentCapable, ApplicationEventPublisher, ResourceLoader{}

@enduml