# settings.yaml
box_name: "bento/centos-stream-9"
vm:
  - name: "master" # 마스터 노드
    ip: "192.168.111.101"
    memory: "4096"
    cpus: "2"
  - name: "node01" # 노드 1
    ip: "192.168.111.102"
    memory: "4096"
    cpus: "2"
  - name: "node02" # 노드 2
    ip: "192.168.111.103"
    memory: "4096"
    cpus: "2"