apiVersion: v1
kind: Pod
metadata:
  name: myweb1
  labels:
    # Pod를 구분하기 위해 라벨 지정
    app: myweb1
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.3-alpine
      ports:
        - containerPort: 80